site_name: Personal Library Manager
site_description: An application to manage your personal library of books, including features for adding, editing, and organizing your book collection.
site_url: https://jeropez.github.io/personal-library-manager/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # modo oscuro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]

nav:
  - Inicio: index.md
  - Guía de usuario: user_guide/guia_usuario.md
  - Guía de instalación: guia_instalacion.md
  - Guía de desarrollo: guia_desarrollo.md
  - Arquitectura del sistema: architecture.md
  - Persistencia de datos: user_guide/persistence.md
  - Referencia técnica:
    - API de python: reference.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
